# Generated by Django 6.1 on 2026-08-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_venue_latitude_venue_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='timezone_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
