# Generated by Django 6.1 on 2026-08-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_venue_timezone_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='venue',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='referee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='round',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
